### model
model_name_or_path: /root/autodl-tmp/models/Qwen2.5-14B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 16
lora_target: all

### dataset
dataset: pokemon,identity
template: qwen
cutoff_len: 1024
max_samples: 160000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
output_dir: saves/Qwen2.5-14B-Instruct/lora/temp
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 3
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
# eval_dataset: alpaca_en_demo
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500




#llamafactory-cli train \
#    --stage sft \
#    --do_train True \
#    --model_name_or_path /root/autodl-tmp/models/Qwen2.5-14B-Instruct \
#    --preprocessing_num_workers 16 \
#    --finetuning_type lora \
#    --template qwen \
#    --rope_scaling dynamic \
#    --flash_attn auto \
#    --dataset_dir data \
#    --dataset pokemon,identity \
#    --cutoff_len 1024 \
#    --learning_rate 5e-05 \
#    --num_train_epochs 1.0 \
#    --max_samples 200000 \
#    --per_device_train_batch_size 3 \
#    --gradient_accumulation_steps 16 \
#    --lr_scheduler_type cosine \
#    --max_grad_norm 2.0 \
#    --logging_steps 10 \
#    --save_steps 100 \
#    --warmup_steps 0 \
#    --packing False \
#    --report_to none \
#    --output_dir temp \
#    --bf16 True \
#    --plot_loss True \
#    --trust_remote_code True \
#    --ddp_timeout 180000000 \
#    --include_num_input_tokens_seen True \
#    --optim adamw_torch \
#    --quantization_bit 4 \
#    --quantization_method bitsandbytes \
#    --double_quantization True \
#    --lora_rank 16 \
#    --lora_alpha 16 \
#    --lora_dropout 0.05 \
#    --lora_target all \
#    --resume_from_checkpoint /root/autodl-tmp/LLaMA-Factory/saves/Qwen2.5-14B-Instruct/lora/train_2025-03-20-15-04-39/checkpoint-12800